CREATE DATABASE IF NOT EXISTS LOJAS;
USE LOJAS;

CREATE TABLE ORDEM_DE_SERVIÇO(
ID INT NOT NULL AUTO_INCREMENT,
PROBLEMA_VEICULO VARCHAR(255),
DATA_ENTRADA DATE,
DATA_RETIRADA DATE,
KM_ENTRADA FLOAT,
KM_RETIRADA FLOAT,
KM_FK FLOAT,
ID_CLIENTE INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
ID_VEICULO INT, 
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (ID_VEICULO),
ID_RECEPCIONISTA INT,
FOREIGN KEY (ID_RECEPCIONISTA) REFERENCES RECEPCIONISTA (ID_RECEPCIONISTA),
PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
ENDEREÇO VARCHAR(255),
COD_CLIENTE VARCHAR(50),
NOME VARCHAR(50),
EMAIL VARCHAR(50),
CNH VARCHAR(11),
DATA_NASCIMENTO DATE,
ID_VEICULO INT, 
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (ID_VEICULO),
PRIMARY KEY (ID_CLIENTE)
);

UPDATE CLIENTE
SET EMAIL = 'catinhoreidelas123@gmail.com'
WHERE ID_CLIENTE = '1';

CREATE TABLE VEICULO (
	ID_VEICULO INT NOT NULL AUTO_INCREMENT,
	PROBLEMA_VEICULO TEXT,
    DATA_ENTRADA DATE,
    DATA_RETIRADA DATE,
    KM_ENTRADA FLOAT,
    KM_RETIRADA FLOAT,
    PRIMARY KEY(ID_VEICULO)
);

CREATE TABLE RECEPCIONISTA(
ID_RECEPCIONISTA INT NOT NULL AUTO_INCREMENT,
COD_ATENDIMENTO VARCHAR(50),
PRIMARY KEY (ID_RECEPCIONISTA)
);

CREATE TABLE TELEFONE(
ID_TELEFONE INT NOT NULL AUTO_INCREMENT,
NUMERO VARCHAR(15),
TIPO ENUM ('fIXO', 'PESSOAL'),
PRIMARY KEY(ID_TELEFONE)
);

INSERT INTO CLIENTE VALUES
(DEFAULT, 'Rua nova esperança', '009', 'Rodriguinho', 'rodriguinho@gmail.com', '998899', '2001-12-31', DEFAULT),
(DEFAULT, 'Rua Padre Marcos Anchienta','099','Caio Victor do Nascimento Moraes','caclei@gmail.com','79793876','2005-12-31', DEFAULT),
(DEFAULT, 'Rua das Flores','099','Nicoly','Nicoly@gmail.com','79793876','2006-12-31', DEFAULT),
(DEFAULT, 'Rua Santa Terezinha ','0878','Ana Laura','AnaLauraReideles@gmail.com','8767669','2007-09-12', DEFAULT),
(DEFAULT, 'C.O', '0099', 'Mark zuckerberg', 'markinho@gmail.com', '9988991', '1995-06-15', DEFAULT); 


SELECT * FROM CLIENTE;

-- ALTER TABLE VEICULO
-- DROP COLUMN KM_FK;

 -- DROP TABLE VEICULO;
-- SELECT * FROM ORDEM_DE_SERVIÇO;
-- DROP DATABASE LOJAS;
