CREATE DATABASE IF NOT EXISTS LOJAS;
USE LOJAS;

CREATE TABLE ORDEM_DE_SERVIÇO(
ID INT NOT NULL AUTO_INCREMENT,
PROBLEMA_VEICULO VARCHAR(255),
DATA_ENTRADA DATE,
DATA_RETIRADA DATE,
KM_ENTRADA FLOAT,
KM_RETIRADA FLOAT,
KM_FK FLOAT,
ID_CLIENTE INT,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
ID_VEICULO INT, 
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (ID_VEICULO),
ID_RECEPCIONISTA INT,
FOREIGN KEY (ID_RECEPCIONISTA) REFERENCES RECEPCIONISTA (ID_RECEPCIONISTA),
PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
ENDEREÇO VARCHAR(255),
COD_CLIENTE VARCHAR(50),
NOME VARCHAR(50),
EMAIL VARCHAR(50),
CNH VARCHAR(11),
DATA_NASCIMENTO DATE,
ID_VEICULO INT, 
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO (ID_VEICULO),
PRIMARY KEY (ID_CLIENTE)
);

SELECT * FROM CLIENTE;

-- DADOS PESSOAS
INSERT INTO CLIENTE 
(ENDEREÇO, COD_CLIENTE, NOME, EMAIL, CNH, DATA_NASCIMENTO)
VALUES
('RUA DOS MARICAS , N24 , JÕAO DE DEUS', '5674', 'KALIL', 'CATINHOMASTER@GMAIL.COM', '32873741238', '2005-12-31');


CREATE TABLE VEICULO (
	ID_VEICULO INT NOT NULL AUTO_INCREMENT,
	PROBLEMA_VEICULO TEXT,
    DATA_ENTRADA DATE,
    DATA_RETIRADA DATE,
    KM_ENTRADA FLOAT,
    KM_RETIRADA FLOAT,
    PRIMARY KEY(ID_VEICULO)
);

INSERT INTO VEICULO 
(PROBLEMA_VEICULO, DATA_ENTRADA, DATA_RETIRADA, KM_ENTRADA, KM_RETIRADA)
VALUES
('CAMBIO MANUAL ESTA COM DEFEITO', '2025-09-20', '2025-11-20', '5000', '6000');

ALTER TABLE VEICULO
MODIFY DATA_RETIRADA DATE DEFAULT '';

CREATE TABLE RECEPCIONISTA(
ID_RECEPCIONISTA INT NOT NULL AUTO_INCREMENT,
COD_ATENDIMENTO VARCHAR(50),
PRIMARY KEY (ID_RECEPCIONISTA)
);

CREATE TABLE TELEFONE(
ID_TELEFONE INT NOT NULL AUTO_INCREMENT,
NUMERO VARCHAR(15),
TIPO ENUM ('fIXO', 'PESSOAL'),
PRIMARY KEY(ID_TELEFONE)
);

-- ALTER TABLE VEICULO
-- DROP COLUMN KM_FK;

 -- DROP TABLE VEICULO;
-- SELECT * FROM ORDEM_DE_SERVIÇO;
-- DROP DATABASE LOJAS;
-- APAGA A POHA TODA 
-- fk = id_cliente , pra isso tu cria na tabela "id_cliente INT" ai logo dps faz aquilo lá de: FOREIGN KEY (id_cliente) REFERENCES Clientes (id_cliente)
