CREATE DATABASE CADASTRO -- DDL DATA DEFINITION LANGUAGE 
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE CADASTRO;

CREATE TABLE PESSOAS(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
NASCIMENTO DATE,
SEXO ENUM ('M','F'),
PESO DECIMAL (5,2),
ALTURA DECIMAL(3,2),
NACIONALIDADE VARCHAR (20) DEFAULT 'Brasil',
PRIMARY KEY(ID)
)DEFAULT CHARSET = utf8;

INSERT INTO PESSOAS VALUES -- DML DATA MANIPULATION LANGUAGE
(DEFAULT, 'Edilson', '1979-01-04', 'M', '101.5', '1.65', 'Brasil'),
(DEFAUlT, 'Cleude','1978-04-24','F','50.0','1.50','Brasil'),
(DEFAULT, 'Ana Beatriz', '2003-10-07', 'F', '60.0', '1.59', 'Brasil'),
(DEFAULT, 'Cato O melhozim da família', '2005-12-31', 'M', '80.0', '1.67', 'Brasil');

SELECT * FROM PESSOAS; 